export const dummy1 = {
  origin: "FOR",
  originAirportName: "Pinto Martins International, Fortaleza - BR",
  finalDestination: "LIS",
  finalDestinationAirportName: "Lisboa, Lisbon - PT",
  passengers: {
    adultNumber: 1,
    childNumber: 0,
    infantNumber: 0,
  },
  departureFlights: {
    date: "26/11/2024",
    flights: [
      {
        id: 1,
        originAirport: "FOR",
        originAirportName: "Pinto Martins International, Fortaleza - BR",
        finalDestination: "LIS",
        finalDestinationName: "Lisboa, Lisbon - PT",
        departureDate: "26/11/2024",
        departureTime: "09:25",
        finalArrivalDate: "27/11/2024",
        finalArrivalTime: "10:35",
        dateVariation: 1,
        firstFlightNumber: 4100,
        operatingCarriers: ["AD", "TP"],
        prices: [
          {
            category: "ECONOMY",
            passenger: "ADULT",
            value: 3653.01,
            differenceValue: null,
            currency: "BRL",
            classType: "PUBLIC",
          },
        ],
        baggage: [
          {
            category: "ECONOMY",
            quantity: 0,
            weight: null,
          },
        ],
        connection: 1,
        hasExchangeAirport: false,
        throughFlight: 0,
        fareOriginType: "PUBLIC",
        recommendations: [
          {
            departureCategory: "ECONOMY",
            departureBookingClass: "M",
            returnFlights: null,
            fee: {
              total: {
                value: 138.76,
                currency: "BRL",
              },
            },
            fare: {
              "48": {
                cabinProduct: "M",
                classOfService: "L",
                fareBasis: "LL0DSI04",
                fareTypes: ["RP"],
              },
              "4100": {
                cabinProduct: "M",
                classOfService: "N",
                fareBasis: "LL0DSI04",
                fareTypes: ["RP"],
              },
            },
            validateCompany: "TP",
            othersFee: [],
          },
        ],
        flightGroup: [
          {
            flightNumber: 4100,
            origin: "FOR",
            originAirportName: "Pinto Martins International, Fortaleza - BR",
            destination: "BEL",
            destinationAirportName: "Val de Cans Intl, Belem - BR",
            departureDate: "26/11/2024",
            departureTime: "09:25",
            arrivalDate: "26/11/2024",
            arrivalTime: "11:25",
            dateVariation: 0,
            marketingCarrier: "AD",
            operatingCarrier: "AD",
            hasExchangeAirport: false,
            throughFlight: false,
          },
          {
            flightNumber: 48,
            origin: "BEL",
            originAirportName: "Val de Cans Intl, Belem - BR",
            destination: "LIS",
            destinationAirportName: "Lisboa, Lisbon - PT",
            departureDate: "26/11/2024",
            departureTime: "23:45",
            arrivalDate: "27/11/2024",
            arrivalTime: "10:35",
            dateVariation: 1,
            marketingCarrier: "TP",
            operatingCarrier: "TP",
            hasExchangeAirport: false,
            throughFlight: false,
          },
        ],
        elapsedFlightTime: "2210",
      },
      {
        id: 2,
        originAirport: "FOR",
        originAirportName: "Pinto Martins International, Fortaleza - BR",
        finalDestination: "LIS",
        finalDestinationName: "Lisboa, Lisbon - PT",
        departureDate: "26/11/2024",
        departureTime: "02:55",
        finalArrivalDate: "27/11/2024",
        finalArrivalTime: "06:20",
        dateVariation: 1,
        firstFlightNumber: 4247,
        operatingCarriers: ["AD", "TP"],
        prices: [
          {
            category: "ECONOMY",
            passenger: "ADULT",
            value: 3899.17,
            differenceValue: null,
            currency: "BRL",
            classType: "PUBLIC",
          },
        ],
        baggage: [
          {
            category: "ECONOMY",
            quantity: 0,
            weight: null,
          },
        ],
        connection: 1,
        hasExchangeAirport: false,
        throughFlight: 0,
        fareOriginType: "PUBLIC",
        recommendations: [
          {
            departureCategory: "ECONOMY",
            departureBookingClass: "M",
            returnFlights: null,
            fee: {
              total: {
                value: 104.77,
                currency: "BRL",
              },
            },
            fare: {
              "104": {
                cabinProduct: "M",
                classOfService: "L",
                fareBasis: "LL0DSI04",
                fareTypes: ["RP"],
              },
              "4247": {
                cabinProduct: "M",
                classOfService: "N",
                fareBasis: "LL0DSI04",
                fareTypes: ["RP"],
              },
            },
            validateCompany: "TP",
            othersFee: [],
          },
        ],
        flightGroup: [
          {
            flightNumber: 4247,
            origin: "FOR",
            originAirportName: "Pinto Martins International, Fortaleza - BR",
            destination: "CNF",
            destinationAirportName:
              "Tancredo Neves International, Belo Horizonte - BR",
            departureDate: "26/11/2024",
            departureTime: "02:55",
            arrivalDate: "26/11/2024",
            arrivalTime: "05:45",
            dateVariation: 0,
            marketingCarrier: "AD",
            operatingCarrier: "AD",
            hasExchangeAirport: false,
            throughFlight: false,
          },
          {
            flightNumber: 104,
            origin: "CNF",
            originAirportName:
              "Tancredo Neves International, Belo Horizonte - BR",
            destination: "LIS",
            destinationAirportName: "Lisboa, Lisbon - PT",
            departureDate: "26/11/2024",
            departureTime: "18:10",
            arrivalDate: "27/11/2024",
            arrivalTime: "06:20",
            dateVariation: 1,
            marketingCarrier: "TP",
            operatingCarrier: "TP",
            hasExchangeAirport: false,
            throughFlight: false,
          },
        ],
        elapsedFlightTime: "2425",
      },
      {
        id: 3,
        originAirport: "FOR",
        originAirportName: "Pinto Martins International, Fortaleza - BR",
        finalDestination: "LIS",
        finalDestinationName: "Lisboa, Lisbon - PT",
        departureDate: "26/11/2024",
        departureTime: "12:45",
        finalArrivalDate: "27/11/2024",
        finalArrivalTime: "14:35",
        dateVariation: 1,
        firstFlightNumber: 4669,
        operatingCarriers: ["AD", "LX"],
        prices: [
          {
            category: "ECONOMY",
            passenger: "ADULT",
            value: 4327.49,
            differenceValue: null,
            currency: "BRL",
            classType: "PUBLIC",
          },
        ],
        baggage: [
          {
            category: "ECONOMY",
            quantity: 1,
            weight: null,
          },
        ],
        connection: 2,
        hasExchangeAirport: true,
        throughFlight: 0,
        fareOriginType: "PUBLIC",
        recommendations: [
          {
            departureCategory: "ECONOMY",
            departureBookingClass: "M",
            returnFlights: null,
            fee: {
              total: {
                value: 289.73,
                currency: "BRL",
              },
            },
            fare: {
              "93": {
                cabinProduct: "M",
                classOfService: "V",
                fareBasis: "VNCOW1BR",
                fareTypes: ["RP"],
              },
              "2084": {
                cabinProduct: "M",
                classOfService: "V",
                fareBasis: "VNCOW1BR",
                fareTypes: ["RP"],
              },
              "4669": {
                cabinProduct: "M",
                classOfService: "Q",
                fareBasis: "VNCOW1BR",
                fareTypes: ["RP"],
              },
            },
            validateCompany: "LX",
            othersFee: [],
          },
        ],
        flightGroup: [
          {
            flightNumber: 4669,
            origin: "FOR",
            originAirportName: "Pinto Martins International, Fortaleza - BR",
            destination: "VCP",
            destinationAirportName:
              "Viracopos-Campinas Intl, Sao Paulo-Viracopos - BR",
            departureDate: "26/11/2024",
            departureTime: "12:45",
            arrivalDate: "26/11/2024",
            arrivalTime: "16:05",
            dateVariation: 0,
            marketingCarrier: "AD",
            operatingCarrier: "AD",
            hasExchangeAirport: false,
            throughFlight: false,
          },
          {
            flightNumber: 93,
            origin: "GRU",
            originAirportName: "Guarulhos Intl, Sao Paulo-Guarulhos - BR",
            destination: "ZRH",
            destinationAirportName: "Zurich - CH",
            departureDate: "26/11/2024",
            departureTime: "19:20",
            arrivalDate: "27/11/2024",
            arrivalTime: "10:30",
            dateVariation: 1,
            marketingCarrier: "LX",
            operatingCarrier: "LX",
            hasExchangeAirport: true,
            throughFlight: false,
          },
          {
            flightNumber: 2084,
            origin: "ZRH",
            originAirportName: "Zurich - CH",
            destination: "LIS",
            destinationAirportName: "Lisboa, Lisbon - PT",
            departureDate: "27/11/2024",
            departureTime: "12:45",
            arrivalDate: "27/11/2024",
            arrivalTime: "14:35",
            dateVariation: 0,
            marketingCarrier: "LX",
            operatingCarrier: "LX",
            hasExchangeAirport: false,
            throughFlight: false,
          },
        ],
        elapsedFlightTime: "2250",
      },
      {
        id: 4,
        originAirport: "FOR",
        originAirportName: "Pinto Martins International, Fortaleza - BR",
        finalDestination: "LIS",
        finalDestinationName: "Lisboa, Lisbon - PT",
        departureDate: "26/11/2024",
        departureTime: "12:45",
        finalArrivalDate: "27/11/2024",
        finalArrivalTime: "15:25",
        dateVariation: 1,
        firstFlightNumber: 4669,
        operatingCarriers: ["AD", "LX", "TP"],
        prices: [
          {
            category: "ECONOMY",
            passenger: "ADULT",
            value: 4327.49,
            differenceValue: null,
            currency: "BRL",
            classType: "PUBLIC",
          },
        ],
        baggage: [
          {
            category: "ECONOMY",
            quantity: 1,
            weight: null,
          },
        ],
        connection: 2,
        hasExchangeAirport: true,
        throughFlight: 0,
        fareOriginType: "PUBLIC",
        recommendations: [
          {
            departureCategory: "ECONOMY",
            departureBookingClass: "M",
            returnFlights: null,
            fee: {
              total: {
                value: 289.73,
                currency: "BRL",
              },
            },
            fare: {
              "93": {
                cabinProduct: "M",
                classOfService: "V",
                fareBasis: "VNCOW1BR",
                fareTypes: ["RP"],
              },
              "4580": {
                cabinProduct: "M",
                classOfService: "V",
                fareBasis: "VNCOW1BR",
                fareTypes: ["RP"],
              },
              "4669": {
                cabinProduct: "M",
                classOfService: "Q",
                fareBasis: "VNCOW1BR",
                fareTypes: ["RP"],
              },
            },
            validateCompany: "LX",
            othersFee: [],
          },
        ],
        flightGroup: [
          {
            flightNumber: 4669,
            origin: "FOR",
            originAirportName: "Pinto Martins International, Fortaleza - BR",
            destination: "VCP",
            destinationAirportName:
              "Viracopos-Campinas Intl, Sao Paulo-Viracopos - BR",
            departureDate: "26/11/2024",
            departureTime: "12:45",
            arrivalDate: "26/11/2024",
            arrivalTime: "16:05",
            dateVariation: 0,
            marketingCarrier: "AD",
            operatingCarrier: "AD",
            hasExchangeAirport: false,
            throughFlight: false,
          },
          {
            flightNumber: 93,
            origin: "GRU",
            originAirportName: "Guarulhos Intl, Sao Paulo-Guarulhos - BR",
            destination: "ZRH",
            destinationAirportName: "Zurich - CH",
            departureDate: "26/11/2024",
            departureTime: "19:20",
            arrivalDate: "27/11/2024",
            arrivalTime: "10:30",
            dateVariation: 1,
            marketingCarrier: "LX",
            operatingCarrier: "LX",
            hasExchangeAirport: true,
            throughFlight: false,
          },
          {
            flightNumber: 4580,
            origin: "ZRH",
            originAirportName: "Zurich - CH",
            destination: "LIS",
            destinationAirportName: "Lisboa, Lisbon - PT",
            departureDate: "27/11/2024",
            departureTime: "13:30",
            arrivalDate: "27/11/2024",
            arrivalTime: "15:25",
            dateVariation: 0,
            marketingCarrier: "LX",
            operatingCarrier: "TP",
            hasExchangeAirport: false,
            throughFlight: false,
          },
        ],
        elapsedFlightTime: "2340",
      },
      {
        id: 5,
        originAirport: "FOR",
        originAirportName: "Pinto Martins International, Fortaleza - BR",
        finalDestination: "LIS",
        finalDestinationName: "Lisboa, Lisbon - PT",
        departureDate: "26/11/2024",
        departureTime: "12:45",
        finalArrivalDate: "27/11/2024",
        finalArrivalTime: "19:50",
        dateVariation: 1,
        firstFlightNumber: 4669,
        operatingCarriers: ["AD", "LX", "TP"],
        prices: [
          {
            category: "ECONOMY",
            passenger: "ADULT",
            value: 4327.49,
            differenceValue: null,
            currency: "BRL",
            classType: "PUBLIC",
          },
        ],
        baggage: [
          {
            category: "ECONOMY",
            quantity: 1,
            weight: null,
          },
        ],
        connection: 2,
        hasExchangeAirport: true,
        throughFlight: 0,
        fareOriginType: "PUBLIC",
        recommendations: [
          {
            departureCategory: "ECONOMY",
            departureBookingClass: "M",
            returnFlights: null,
            fee: {
              total: {
                value: 289.73,
                currency: "BRL",
              },
            },
            fare: {
              "93": {
                cabinProduct: "M",
                classOfService: "V",
                fareBasis: "VNCOW1BR",
                fareTypes: ["RP"],
              },
              "4590": {
                cabinProduct: "M",
                classOfService: "V",
                fareBasis: "VNCOW1BR",
                fareTypes: ["RP"],
              },
              "4669": {
                cabinProduct: "M",
                classOfService: "Q",
                fareBasis: "VNCOW1BR",
                fareTypes: ["RP"],
              },
            },
            validateCompany: "LX",
            othersFee: [],
          },
        ],
        flightGroup: [
          {
            flightNumber: 4669,
            origin: "FOR",
            originAirportName: "Pinto Martins International, Fortaleza - BR",
            destination: "VCP",
            destinationAirportName:
              "Viracopos-Campinas Intl, Sao Paulo-Viracopos - BR",
            departureDate: "26/11/2024",
            departureTime: "12:45",
            arrivalDate: "26/11/2024",
            arrivalTime: "16:05",
            dateVariation: 0,
            marketingCarrier: "AD",
            operatingCarrier: "AD",
            hasExchangeAirport: false,
            throughFlight: false,
          },
          {
            flightNumber: 93,
            origin: "GRU",
            originAirportName: "Guarulhos Intl, Sao Paulo-Guarulhos - BR",
            destination: "ZRH",
            destinationAirportName: "Zurich - CH",
            departureDate: "26/11/2024",
            departureTime: "19:20",
            arrivalDate: "27/11/2024",
            arrivalTime: "10:30",
            dateVariation: 1,
            marketingCarrier: "LX",
            operatingCarrier: "LX",
            hasExchangeAirport: true,
            throughFlight: false,
          },
          {
            flightNumber: 4590,
            origin: "ZRH",
            originAirportName: "Zurich - CH",
            destination: "LIS",
            destinationAirportName: "Lisboa, Lisbon - PT",
            departureDate: "27/11/2024",
            departureTime: "18:00",
            arrivalDate: "27/11/2024",
            arrivalTime: "19:50",
            dateVariation: 0,
            marketingCarrier: "LX",
            operatingCarrier: "TP",
            hasExchangeAirport: false,
            throughFlight: false,
          },
        ],
        elapsedFlightTime: "2805",
      },
      {
        id: 6,
        originAirport: "FOR",
        originAirportName: "Pinto Martins International, Fortaleza - BR",
        finalDestination: "LIS",
        finalDestinationName: "Lisboa, Lisbon - PT",
        departureDate: "26/11/2024",
        departureTime: "12:45",
        finalArrivalDate: "28/11/2024",
        finalArrivalTime: "06:50",
        dateVariation: 2,
        firstFlightNumber: 4669,
        operatingCarriers: ["AD", "UX"],
        prices: [
          {
            category: "ECONOMY",
            passenger: "ADULT",
            value: 4504.72,
            differenceValue: null,
            currency: "BRL",
            classType: "PUBLIC",
          },
        ],
        baggage: [
          {
            category: "ECONOMY",
            quantity: 1,
            weight: null,
          },
        ],
        connection: 2,
        hasExchangeAirport: true,
        throughFlight: 0,
        fareOriginType: "PUBLIC",
        recommendations: [
          {
            departureCategory: "ECONOMY",
            departureBookingClass: "M",
            returnFlights: null,
            fee: {
              total: {
                value: 166.95,
                currency: "BRL",
              },
            },
            fare: {
              "58": {
                cabinProduct: "M",
                classOfService: "S",
                fareBasis: "SLYOAENE",
                fareTypes: ["RA"],
              },
              "1159": {
                cabinProduct: "M",
                classOfService: "S",
                fareBasis: "SLYOAENE",
                fareTypes: ["RA"],
              },
              "4669": {
                cabinProduct: "M",
                classOfService: "P",
                fareBasis: "SLYOAENE",
                fareTypes: ["RA"],
              },
            },
            validateCompany: "UX",
            othersFee: [],
          },
        ],
        flightGroup: [
          {
            flightNumber: 4669,
            origin: "FOR",
            originAirportName: "Pinto Martins International, Fortaleza - BR",
            destination: "VCP",
            destinationAirportName:
              "Viracopos-Campinas Intl, Sao Paulo-Viracopos - BR",
            departureDate: "26/11/2024",
            departureTime: "12:45",
            arrivalDate: "26/11/2024",
            arrivalTime: "16:05",
            dateVariation: 0,
            marketingCarrier: "AD",
            operatingCarrier: "AD",
            hasExchangeAirport: false,
            throughFlight: false,
          },
          {
            flightNumber: 58,
            origin: "GRU",
            originAirportName: "Guarulhos Intl, Sao Paulo-Guarulhos - BR",
            destination: "MAD",
            destinationAirportName: "Adolfo Suarez-Barajas, Madrid - ES",
            departureDate: "27/11/2024",
            departureTime: "15:05",
            arrivalDate: "28/11/2024",
            arrivalTime: "05:15",
            dateVariation: 1,
            marketingCarrier: "UX",
            operatingCarrier: "UX",
            hasExchangeAirport: true,
            throughFlight: false,
          },
          {
            flightNumber: 1159,
            origin: "MAD",
            originAirportName: "Adolfo Suarez-Barajas, Madrid - ES",
            destination: "LIS",
            destinationAirportName: "Lisboa, Lisbon - PT",
            departureDate: "28/11/2024",
            departureTime: "06:30",
            arrivalDate: "28/11/2024",
            arrivalTime: "06:50",
            dateVariation: 0,
            marketingCarrier: "UX",
            operatingCarrier: "UX",
            hasExchangeAirport: false,
            throughFlight: false,
          },
        ],
        elapsedFlightTime: "3905",
      },
      {
        id: 7,
        originAirport: "FOR",
        originAirportName: "Pinto Martins International, Fortaleza - BR",
        finalDestination: "LIS",
        finalDestinationName: "Lisboa, Lisbon - PT",
        departureDate: "26/11/2024",
        departureTime: "12:45",
        finalArrivalDate: "28/11/2024",
        finalArrivalTime: "10:45",
        dateVariation: 2,
        firstFlightNumber: 4669,
        operatingCarriers: ["AD", "UX"],
        prices: [
          {
            category: "ECONOMY",
            passenger: "ADULT",
            value: 4504.72,
            differenceValue: null,
            currency: "BRL",
            classType: "PUBLIC",
          },
        ],
        baggage: [
          {
            category: "ECONOMY",
            quantity: 1,
            weight: null,
          },
        ],
        connection: 2,
        hasExchangeAirport: true,
        throughFlight: 0,
        fareOriginType: "PUBLIC",
        recommendations: [
          {
            departureCategory: "ECONOMY",
            departureBookingClass: "M",
            returnFlights: null,
            fee: {
              total: {
                value: 166.95,
                currency: "BRL",
              },
            },
            fare: {
              "58": {
                cabinProduct: "M",
                classOfService: "S",
                fareBasis: "SLYOAENE",
                fareTypes: ["RA"],
              },
              "1153": {
                cabinProduct: "M",
                classOfService: "S",
                fareBasis: "SLYOAENE",
                fareTypes: ["RA"],
              },
              "4669": {
                cabinProduct: "M",
                classOfService: "P",
                fareBasis: "SLYOAENE",
                fareTypes: ["RA"],
              },
            },
            validateCompany: "UX",
            othersFee: [],
          },
        ],
        flightGroup: [
          {
            flightNumber: 4669,
            origin: "FOR",
            originAirportName: "Pinto Martins International, Fortaleza - BR",
            destination: "VCP",
            destinationAirportName:
              "Viracopos-Campinas Intl, Sao Paulo-Viracopos - BR",
            departureDate: "26/11/2024",
            departureTime: "12:45",
            arrivalDate: "26/11/2024",
            arrivalTime: "16:05",
            dateVariation: 0,
            marketingCarrier: "AD",
            operatingCarrier: "AD",
            hasExchangeAirport: false,
            throughFlight: false,
          },
          {
            flightNumber: 58,
            origin: "GRU",
            originAirportName: "Guarulhos Intl, Sao Paulo-Guarulhos - BR",
            destination: "MAD",
            destinationAirportName: "Adolfo Suarez-Barajas, Madrid - ES",
            departureDate: "27/11/2024",
            departureTime: "15:05",
            arrivalDate: "28/11/2024",
            arrivalTime: "05:15",
            dateVariation: 1,
            marketingCarrier: "UX",
            operatingCarrier: "UX",
            hasExchangeAirport: true,
            throughFlight: false,
          },
          {
            flightNumber: 1153,
            origin: "MAD",
            originAirportName: "Adolfo Suarez-Barajas, Madrid - ES",
            destination: "LIS",
            destinationAirportName: "Lisboa, Lisbon - PT",
            departureDate: "28/11/2024",
            departureTime: "10:25",
            arrivalDate: "28/11/2024",
            arrivalTime: "10:45",
            dateVariation: 0,
            marketingCarrier: "UX",
            operatingCarrier: "UX",
            hasExchangeAirport: false,
            throughFlight: false,
          },
        ],
        elapsedFlightTime: "4300",
      },
      {
        id: 8,
        originAirport: "FOR",
        originAirportName: "Pinto Martins International, Fortaleza - BR",
        finalDestination: "LIS",
        finalDestinationName: "Lisboa, Lisbon - PT",
        departureDate: "26/11/2024",
        departureTime: "12:45",
        finalArrivalDate: "28/11/2024",
        finalArrivalTime: "15:15",
        dateVariation: 2,
        firstFlightNumber: 4669,
        operatingCarriers: ["AD", "UX"],
        prices: [
          {
            category: "ECONOMY",
            passenger: "ADULT",
            value: 4504.72,
            differenceValue: null,
            currency: "BRL",
            classType: "PUBLIC",
          },
        ],
        baggage: [
          {
            category: "ECONOMY",
            quantity: 1,
            weight: null,
          },
        ],
        connection: 2,
        hasExchangeAirport: true,
        throughFlight: 0,
        fareOriginType: "PUBLIC",
        recommendations: [
          {
            departureCategory: "ECONOMY",
            departureBookingClass: "M",
            returnFlights: null,
            fee: {
              total: {
                value: 166.95,
                currency: "BRL",
              },
            },
            fare: {
              "58": {
                cabinProduct: "M",
                classOfService: "S",
                fareBasis: "SLYOAENE",
                fareTypes: ["RA"],
              },
              "1155": {
                cabinProduct: "M",
                classOfService: "S",
                fareBasis: "SLYOAENE",
                fareTypes: ["RA"],
              },
              "4669": {
                cabinProduct: "M",
                classOfService: "P",
                fareBasis: "SLYOAENE",
                fareTypes: ["RA"],
              },
            },
            validateCompany: "UX",
            othersFee: [],
          },
        ],
        flightGroup: [
          {
            flightNumber: 4669,
            origin: "FOR",
            originAirportName: "Pinto Martins International, Fortaleza - BR",
            destination: "VCP",
            destinationAirportName:
              "Viracopos-Campinas Intl, Sao Paulo-Viracopos - BR",
            departureDate: "26/11/2024",
            departureTime: "12:45",
            arrivalDate: "26/11/2024",
            arrivalTime: "16:05",
            dateVariation: 0,
            marketingCarrier: "AD",
            operatingCarrier: "AD",
            hasExchangeAirport: false,
            throughFlight: false,
          },
          {
            flightNumber: 58,
            origin: "GRU",
            originAirportName: "Guarulhos Intl, Sao Paulo-Guarulhos - BR",
            destination: "MAD",
            destinationAirportName: "Adolfo Suarez-Barajas, Madrid - ES",
            departureDate: "27/11/2024",
            departureTime: "15:05",
            arrivalDate: "28/11/2024",
            arrivalTime: "05:15",
            dateVariation: 1,
            marketingCarrier: "UX",
            operatingCarrier: "UX",
            hasExchangeAirport: true,
            throughFlight: false,
          },
          {
            flightNumber: 1155,
            origin: "MAD",
            originAirportName: "Adolfo Suarez-Barajas, Madrid - ES",
            destination: "LIS",
            destinationAirportName: "Lisboa, Lisbon - PT",
            departureDate: "28/11/2024",
            departureTime: "14:55",
            arrivalDate: "28/11/2024",
            arrivalTime: "15:15",
            dateVariation: 0,
            marketingCarrier: "UX",
            operatingCarrier: "UX",
            hasExchangeAirport: false,
            throughFlight: false,
          },
        ],
        elapsedFlightTime: "4730",
      },
      {
        id: 9,
        originAirport: "FOR",
        originAirportName: "Pinto Martins International, Fortaleza - BR",
        finalDestination: "LIS",
        finalDestinationName: "Lisboa, Lisbon - PT",
        departureDate: "26/11/2024",
        departureTime: "12:45",
        finalArrivalDate: "27/11/2024",
        finalArrivalTime: "12:10",
        dateVariation: 1,
        firstFlightNumber: 4669,
        operatingCarriers: ["AD", "TP"],
        prices: [
          {
            category: "ECONOMY",
            passenger: "ADULT",
            value: 4578.57,
            differenceValue: null,
            currency: "BRL",
            classType: "PUBLIC",
          },
        ],
        baggage: [
          {
            category: "ECONOMY",
            quantity: 0,
            weight: null,
          },
        ],
        connection: 1,
        hasExchangeAirport: true,
        throughFlight: 0,
        fareOriginType: "PUBLIC",
        recommendations: [
          {
            departureCategory: "ECONOMY",
            departureBookingClass: "M",
            returnFlights: null,
            fee: {
              total: {
                value: 105.17,
                currency: "BRL",
              },
            },
            fare: {
              "88": {
                cabinProduct: "M",
                classOfService: "A",
                fareBasis: "AL0DSI04",
                fareTypes: ["RP"],
              },
              "4669": {
                cabinProduct: "M",
                classOfService: "L",
                fareBasis: "AL0DSI04",
                fareTypes: ["RP"],
              },
            },
            validateCompany: "TP",
            othersFee: [],
          },
        ],
        flightGroup: [
          {
            flightNumber: 4669,
            origin: "FOR",
            originAirportName: "Pinto Martins International, Fortaleza - BR",
            destination: "VCP",
            destinationAirportName:
              "Viracopos-Campinas Intl, Sao Paulo-Viracopos - BR",
            departureDate: "26/11/2024",
            departureTime: "12:45",
            arrivalDate: "26/11/2024",
            arrivalTime: "16:05",
            dateVariation: 0,
            marketingCarrier: "AD",
            operatingCarrier: "AD",
            hasExchangeAirport: false,
            throughFlight: false,
          },
          {
            flightNumber: 88,
            origin: "GRU",
            originAirportName: "Guarulhos Intl, Sao Paulo-Guarulhos - BR",
            destination: "LIS",
            destinationAirportName: "Lisboa, Lisbon - PT",
            departureDate: "26/11/2024",
            departureTime: "23:15",
            arrivalDate: "27/11/2024",
            arrivalTime: "12:10",
            dateVariation: 1,
            marketingCarrier: "TP",
            operatingCarrier: "TP",
            hasExchangeAirport: true,
            throughFlight: false,
          },
        ],
        elapsedFlightTime: "2025",
      },
      {
        id: 10,
        originAirport: "FOR",
        originAirportName: "Pinto Martins International, Fortaleza - BR",
        finalDestination: "LIS",
        finalDestinationName: "Lisboa, Lisbon - PT",
        departureDate: "26/11/2024",
        departureTime: "12:45",
        finalArrivalDate: "28/11/2024",
        finalArrivalTime: "19:15",
        dateVariation: 2,
        firstFlightNumber: 4669,
        operatingCarriers: ["AD", "UX"],
        prices: [
          {
            category: "ECONOMY",
            passenger: "ADULT",
            value: 4504.72,
            differenceValue: null,
            currency: "BRL",
            classType: "PUBLIC",
          },
        ],
        baggage: [
          {
            category: "ECONOMY",
            quantity: 1,
            weight: null,
          },
        ],
        connection: 2,
        hasExchangeAirport: true,
        throughFlight: 0,
        fareOriginType: "PUBLIC",
        recommendations: [
          {
            departureCategory: "ECONOMY",
            departureBookingClass: "M",
            returnFlights: null,
            fee: {
              total: {
                value: 203.5,
                currency: "BRL",
              },
            },
            fare: {
              "58": {
                cabinProduct: "M",
                classOfService: "S",
                fareBasis: "SLYOAENE",
                fareTypes: ["RA"],
              },
              "1157": {
                cabinProduct: "M",
                classOfService: "S",
                fareBasis: "SLYOAENE",
                fareTypes: ["RA"],
              },
              "4669": {
                cabinProduct: "M",
                classOfService: "P",
                fareBasis: "SLYOAENE",
                fareTypes: ["RA"],
              },
            },
            validateCompany: "UX",
            othersFee: [],
          },
        ],
        flightGroup: [
          {
            flightNumber: 4669,
            origin: "FOR",
            originAirportName: "Pinto Martins International, Fortaleza - BR",
            destination: "VCP",
            destinationAirportName:
              "Viracopos-Campinas Intl, Sao Paulo-Viracopos - BR",
            departureDate: "26/11/2024",
            departureTime: "12:45",
            arrivalDate: "26/11/2024",
            arrivalTime: "16:05",
            dateVariation: 0,
            marketingCarrier: "AD",
            operatingCarrier: "AD",
            hasExchangeAirport: false,
            throughFlight: false,
          },
          {
            flightNumber: 58,
            origin: "GRU",
            originAirportName: "Guarulhos Intl, Sao Paulo-Guarulhos - BR",
            destination: "MAD",
            destinationAirportName: "Adolfo Suarez-Barajas, Madrid - ES",
            departureDate: "27/11/2024",
            departureTime: "15:05",
            arrivalDate: "28/11/2024",
            arrivalTime: "05:15",
            dateVariation: 1,
            marketingCarrier: "UX",
            operatingCarrier: "UX",
            hasExchangeAirport: true,
            throughFlight: false,
          },
          {
            flightNumber: 1157,
            origin: "MAD",
            originAirportName: "Adolfo Suarez-Barajas, Madrid - ES",
            destination: "LIS",
            destinationAirportName: "Lisboa, Lisbon - PT",
            departureDate: "28/11/2024",
            departureTime: "18:55",
            arrivalDate: "28/11/2024",
            arrivalTime: "19:15",
            dateVariation: 0,
            marketingCarrier: "UX",
            operatingCarrier: "UX",
            hasExchangeAirport: false,
            throughFlight: false,
          },
        ],
        elapsedFlightTime: "5130",
      },
      {
        id: 11,
        originAirport: "FOR",
        originAirportName: "Pinto Martins International, Fortaleza - BR",
        finalDestination: "LIS",
        finalDestinationName: "Lisboa, Lisbon - PT",
        departureDate: "26/11/2024",
        departureTime: "11:40",
        finalArrivalDate: "27/11/2024",
        finalArrivalTime: "16:05",
        dateVariation: 1,
        firstFlightNumber: 6497,
        operatingCarriers: ["IB"],
        prices: [
          {
            category: "ECONOMY",
            passenger: "ADULT",
            value: 5016.74,
            differenceValue: null,
            currency: "BRL",
            classType: "PUBLIC",
          },
        ],
        baggage: [
          {
            category: "ECONOMY",
            quantity: 1,
            weight: null,
          },
        ],
        connection: 2,
        hasExchangeAirport: false,
        throughFlight: 0,
        fareOriginType: "PUBLIC",
        recommendations: [
          {
            departureCategory: "ECONOMY",
            departureBookingClass: "M",
            returnFlights: null,
            fee: {
              total: {
                value: 166.95,
                currency: "BRL",
              },
            },
            fare: {
              "272": {
                cabinProduct: "M",
                classOfService: "L",
                fareBasis: "LDL0NOM7",
                fareTypes: ["RP"],
              },
              "533": {
                cabinProduct: "M",
                classOfService: "L",
                fareBasis: "LDL0NOM7",
                fareTypes: ["RP"],
              },
              "6497": {
                cabinProduct: "M",
                classOfService: "O",
                fareBasis: "LDL0NOM7",
                fareTypes: ["RP"],
              },
            },
            validateCompany: "IB",
            othersFee: [],
          },
        ],
        flightGroup: [
          {
            flightNumber: 6497,
            origin: "FOR",
            originAirportName: "Pinto Martins International, Fortaleza - BR",
            destination: "GRU",
            destinationAirportName: "Guarulhos Intl, Sao Paulo-Guarulhos - BR",
            departureDate: "26/11/2024",
            departureTime: "11:40",
            arrivalDate: "26/11/2024",
            arrivalTime: "15:10",
            dateVariation: 0,
            marketingCarrier: "IB",
            operatingCarrier: "IB",
            hasExchangeAirport: false,
            throughFlight: false,
          },
          {
            flightNumber: 272,
            origin: "GRU",
            originAirportName: "Guarulhos Intl, Sao Paulo-Guarulhos - BR",
            destination: "MAD",
            destinationAirportName: "Adolfo Suarez-Barajas, Madrid - ES",
            departureDate: "26/11/2024",
            departureTime: "20:30",
            arrivalDate: "27/11/2024",
            arrivalTime: "10:35",
            dateVariation: 1,
            marketingCarrier: "IB",
            operatingCarrier: "IB",
            hasExchangeAirport: false,
            throughFlight: false,
          },
          {
            flightNumber: 533,
            origin: "MAD",
            originAirportName: "Adolfo Suarez-Barajas, Madrid - ES",
            destination: "LIS",
            destinationAirportName: "Lisboa, Lisbon - PT",
            departureDate: "27/11/2024",
            departureTime: "15:40",
            arrivalDate: "27/11/2024",
            arrivalTime: "16:05",
            dateVariation: 0,
            marketingCarrier: "IB",
            operatingCarrier: "IB",
            hasExchangeAirport: false,
            throughFlight: false,
          },
        ],
        elapsedFlightTime: "2525",
      },
      {
        id: 12,
        originAirport: "FOR",
        originAirportName: "Pinto Martins International, Fortaleza - BR",
        finalDestination: "LIS",
        finalDestinationName: "Lisboa, Lisbon - PT",
        departureDate: "26/11/2024",
        departureTime: "11:40",
        finalArrivalDate: "27/11/2024",
        finalArrivalTime: "18:05",
        dateVariation: 1,
        firstFlightNumber: 6497,
        operatingCarriers: ["IB"],
        prices: [
          {
            category: "ECONOMY",
            passenger: "ADULT",
            value: 5016.74,
            differenceValue: null,
            currency: "BRL",
            classType: "PUBLIC",
          },
        ],
        baggage: [
          {
            category: "ECONOMY",
            quantity: 1,
            weight: null,
          },
        ],
        connection: 2,
        hasExchangeAirport: false,
        throughFlight: 0,
        fareOriginType: "PUBLIC",
        recommendations: [
          {
            departureCategory: "ECONOMY",
            departureBookingClass: "M",
            returnFlights: null,
            fee: {
              total: {
                value: 166.95,
                currency: "BRL",
              },
            },
            fare: {
              "272": {
                cabinProduct: "M",
                classOfService: "L",
                fareBasis: "LDL0NOM7",
                fareTypes: ["RP"],
              },
              "535": {
                cabinProduct: "M",
                classOfService: "L",
                fareBasis: "LDL0NOM7",
                fareTypes: ["RP"],
              },
              "6497": {
                cabinProduct: "M",
                classOfService: "O",
                fareBasis: "LDL0NOM7",
                fareTypes: ["RP"],
              },
            },
            validateCompany: "IB",
            othersFee: [],
          },
        ],
        flightGroup: [
          {
            flightNumber: 6497,
            origin: "FOR",
            originAirportName: "Pinto Martins International, Fortaleza - BR",
            destination: "GRU",
            destinationAirportName: "Guarulhos Intl, Sao Paulo-Guarulhos - BR",
            departureDate: "26/11/2024",
            departureTime: "11:40",
            arrivalDate: "26/11/2024",
            arrivalTime: "15:10",
            dateVariation: 0,
            marketingCarrier: "IB",
            operatingCarrier: "IB",
            hasExchangeAirport: false,
            throughFlight: false,
          },
          {
            flightNumber: 272,
            origin: "GRU",
            originAirportName: "Guarulhos Intl, Sao Paulo-Guarulhos - BR",
            destination: "MAD",
            destinationAirportName: "Adolfo Suarez-Barajas, Madrid - ES",
            departureDate: "26/11/2024",
            departureTime: "20:30",
            arrivalDate: "27/11/2024",
            arrivalTime: "10:35",
            dateVariation: 1,
            marketingCarrier: "IB",
            operatingCarrier: "IB",
            hasExchangeAirport: false,
            throughFlight: false,
          },
          {
            flightNumber: 535,
            origin: "MAD",
            originAirportName: "Adolfo Suarez-Barajas, Madrid - ES",
            destination: "LIS",
            destinationAirportName: "Lisboa, Lisbon - PT",
            departureDate: "27/11/2024",
            departureTime: "17:45",
            arrivalDate: "27/11/2024",
            arrivalTime: "18:05",
            dateVariation: 0,
            marketingCarrier: "IB",
            operatingCarrier: "IB",
            hasExchangeAirport: false,
            throughFlight: false,
          },
        ],
        elapsedFlightTime: "2725",
      },
      {
        id: 13,
        originAirport: "FOR",
        originAirportName: "Pinto Martins International, Fortaleza - BR",
        finalDestination: "LIS",
        finalDestinationName: "Lisboa, Lisbon - PT",
        departureDate: "26/11/2024",
        departureTime: "11:40",
        finalArrivalDate: "27/11/2024",
        finalArrivalTime: "20:05",
        dateVariation: 1,
        firstFlightNumber: 6497,
        operatingCarriers: ["IB"],
        prices: [
          {
            category: "ECONOMY",
            passenger: "ADULT",
            value: 5016.74,
            differenceValue: null,
            currency: "BRL",
            classType: "PUBLIC",
          },
        ],
        baggage: [
          {
            category: "ECONOMY",
            quantity: 1,
            weight: null,
          },
        ],
        connection: 2,
        hasExchangeAirport: false,
        throughFlight: 0,
        fareOriginType: "PUBLIC",
        recommendations: [
          {
            departureCategory: "ECONOMY",
            departureBookingClass: "M",
            returnFlights: null,
            fee: {
              total: {
                value: 166.95,
                currency: "BRL",
              },
            },
            fare: {
              "272": {
                cabinProduct: "M",
                classOfService: "L",
                fareBasis: "LDL0NOM7",
                fareTypes: ["RP"],
              },
              "537": {
                cabinProduct: "M",
                classOfService: "L",
                fareBasis: "LDL0NOM7",
                fareTypes: ["RP"],
              },
              "6497": {
                cabinProduct: "M",
                classOfService: "O",
                fareBasis: "LDL0NOM7",
                fareTypes: ["RP"],
              },
            },
            validateCompany: "IB",
            othersFee: [],
          },
        ],
        flightGroup: [
          {
            flightNumber: 6497,
            origin: "FOR",
            originAirportName: "Pinto Martins International, Fortaleza - BR",
            destination: "GRU",
            destinationAirportName: "Guarulhos Intl, Sao Paulo-Guarulhos - BR",
            departureDate: "26/11/2024",
            departureTime: "11:40",
            arrivalDate: "26/11/2024",
            arrivalTime: "15:10",
            dateVariation: 0,
            marketingCarrier: "IB",
            operatingCarrier: "IB",
            hasExchangeAirport: false,
            throughFlight: false,
          },
          {
            flightNumber: 272,
            origin: "GRU",
            originAirportName: "Guarulhos Intl, Sao Paulo-Guarulhos - BR",
            destination: "MAD",
            destinationAirportName: "Adolfo Suarez-Barajas, Madrid - ES",
            departureDate: "26/11/2024",
            departureTime: "20:30",
            arrivalDate: "27/11/2024",
            arrivalTime: "10:35",
            dateVariation: 1,
            marketingCarrier: "IB",
            operatingCarrier: "IB",
            hasExchangeAirport: false,
            throughFlight: false,
          },
          {
            flightNumber: 537,
            origin: "MAD",
            originAirportName: "Adolfo Suarez-Barajas, Madrid - ES",
            destination: "LIS",
            destinationAirportName: "Lisboa, Lisbon - PT",
            departureDate: "27/11/2024",
            departureTime: "19:40",
            arrivalDate: "27/11/2024",
            arrivalTime: "20:05",
            dateVariation: 0,
            marketingCarrier: "IB",
            operatingCarrier: "IB",
            hasExchangeAirport: false,
            throughFlight: false,
          },
        ],
        elapsedFlightTime: "2925",
      },
      {
        id: 14,
        originAirport: "FOR",
        originAirportName: "Pinto Martins International, Fortaleza - BR",
        finalDestination: "LIS",
        finalDestinationName: "Lisboa, Lisbon - PT",
        departureDate: "26/11/2024",
        departureTime: "11:40",
        finalArrivalDate: "27/11/2024",
        finalArrivalTime: "16:05",
        dateVariation: 1,
        firstFlightNumber: 6497,
        operatingCarriers: ["IB"],
        prices: [
          {
            category: "ECONOMY",
            passenger: "ADULT",
            value: 5016.74,
            differenceValue: null,
            currency: "BRL",
            classType: "PUBLIC",
          },
        ],
        baggage: [
          {
            category: "ECONOMY",
            quantity: 1,
            weight: null,
          },
        ],
        connection: 2,
        hasExchangeAirport: false,
        throughFlight: 0,
        fareOriginType: "PUBLIC",
        recommendations: [
          {
            departureCategory: "ECONOMY",
            departureBookingClass: "M",
            returnFlights: null,
            fee: {
              total: {
                value: 166.95,
                currency: "BRL",
              },
            },
            fare: {
              "533": {
                cabinProduct: "M",
                classOfService: "L",
                fareBasis: "LDL0NOM7",
                fareTypes: ["RP"],
              },
              "6497": {
                cabinProduct: "M",
                classOfService: "O",
                fareBasis: "LDL0NOM7",
                fareTypes: ["RP"],
              },
              "6540": {
                cabinProduct: "M",
                classOfService: "L",
                fareBasis: "LDL0NOM7",
                fareTypes: ["RP"],
              },
            },
            validateCompany: "IB",
            othersFee: [],
          },
        ],
        flightGroup: [
          {
            flightNumber: 6497,
            origin: "FOR",
            originAirportName: "Pinto Martins International, Fortaleza - BR",
            destination: "GRU",
            destinationAirportName: "Guarulhos Intl, Sao Paulo-Guarulhos - BR",
            departureDate: "26/11/2024",
            departureTime: "11:40",
            arrivalDate: "26/11/2024",
            arrivalTime: "15:10",
            dateVariation: 0,
            marketingCarrier: "IB",
            operatingCarrier: "IB",
            hasExchangeAirport: false,
            throughFlight: false,
          },
          {
            flightNumber: 6540,
            origin: "GRU",
            originAirportName: "Guarulhos Intl, Sao Paulo-Guarulhos - BR",
            destination: "MAD",
            destinationAirportName: "Adolfo Suarez-Barajas, Madrid - ES",
            departureDate: "26/11/2024",
            departureTime: "23:30",
            arrivalDate: "27/11/2024",
            arrivalTime: "13:30",
            dateVariation: 1,
            marketingCarrier: "IB",
            operatingCarrier: "IB",
            hasExchangeAirport: false,
            throughFlight: false,
          },
          {
            flightNumber: 533,
            origin: "MAD",
            originAirportName: "Adolfo Suarez-Barajas, Madrid - ES",
            destination: "LIS",
            destinationAirportName: "Lisboa, Lisbon - PT",
            departureDate: "27/11/2024",
            departureTime: "15:40",
            arrivalDate: "27/11/2024",
            arrivalTime: "16:05",
            dateVariation: 0,
            marketingCarrier: "IB",
            operatingCarrier: "IB",
            hasExchangeAirport: false,
            throughFlight: false,
          },
        ],
        elapsedFlightTime: "2525",
      },
      {
        id: 15,
        originAirport: "FOR",
        originAirportName: "Pinto Martins International, Fortaleza - BR",
        finalDestination: "LIS",
        finalDestinationName: "Lisboa, Lisbon - PT",
        departureDate: "26/11/2024",
        departureTime: "11:40",
        finalArrivalDate: "27/11/2024",
        finalArrivalTime: "18:05",
        dateVariation: 1,
        firstFlightNumber: 6497,
        operatingCarriers: ["IB"],
        prices: [
          {
            category: "ECONOMY",
            passenger: "ADULT",
            value: 5016.74,
            differenceValue: null,
            currency: "BRL",
            classType: "PUBLIC",
          },
        ],
        baggage: [
          {
            category: "ECONOMY",
            quantity: 1,
            weight: null,
          },
        ],
        connection: 2,
        hasExchangeAirport: false,
        throughFlight: 0,
        fareOriginType: "PUBLIC",
        recommendations: [
          {
            departureCategory: "ECONOMY",
            departureBookingClass: "M",
            returnFlights: null,
            fee: {
              total: {
                value: 166.95,
                currency: "BRL",
              },
            },
            fare: {
              "535": {
                cabinProduct: "M",
                classOfService: "L",
                fareBasis: "LDL0NOM7",
                fareTypes: ["RP"],
              },
              "6497": {
                cabinProduct: "M",
                classOfService: "O",
                fareBasis: "LDL0NOM7",
                fareTypes: ["RP"],
              },
              "6540": {
                cabinProduct: "M",
                classOfService: "L",
                fareBasis: "LDL0NOM7",
                fareTypes: ["RP"],
              },
            },
            validateCompany: "IB",
            othersFee: [],
          },
        ],
        flightGroup: [
          {
            flightNumber: 6497,
            origin: "FOR",
            originAirportName: "Pinto Martins International, Fortaleza - BR",
            destination: "GRU",
            destinationAirportName: "Guarulhos Intl, Sao Paulo-Guarulhos - BR",
            departureDate: "26/11/2024",
            departureTime: "11:40",
            arrivalDate: "26/11/2024",
            arrivalTime: "15:10",
            dateVariation: 0,
            marketingCarrier: "IB",
            operatingCarrier: "IB",
            hasExchangeAirport: false,
            throughFlight: false,
          },
          {
            flightNumber: 6540,
            origin: "GRU",
            originAirportName: "Guarulhos Intl, Sao Paulo-Guarulhos - BR",
            destination: "MAD",
            destinationAirportName: "Adolfo Suarez-Barajas, Madrid - ES",
            departureDate: "26/11/2024",
            departureTime: "23:30",
            arrivalDate: "27/11/2024",
            arrivalTime: "13:30",
            dateVariation: 1,
            marketingCarrier: "IB",
            operatingCarrier: "IB",
            hasExchangeAirport: false,
            throughFlight: false,
          },
          {
            flightNumber: 535,
            origin: "MAD",
            originAirportName: "Adolfo Suarez-Barajas, Madrid - ES",
            destination: "LIS",
            destinationAirportName: "Lisboa, Lisbon - PT",
            departureDate: "27/11/2024",
            departureTime: "17:45",
            arrivalDate: "27/11/2024",
            arrivalTime: "18:05",
            dateVariation: 0,
            marketingCarrier: "IB",
            operatingCarrier: "IB",
            hasExchangeAirport: false,
            throughFlight: false,
          },
        ],
        elapsedFlightTime: "2725",
      },
      {
        id: 16,
        originAirport: "FOR",
        originAirportName: "Pinto Martins International, Fortaleza - BR",
        finalDestination: "LIS",
        finalDestinationName: "Lisboa, Lisbon - PT",
        departureDate: "26/11/2024",
        departureTime: "11:40",
        finalArrivalDate: "27/11/2024",
        finalArrivalTime: "20:05",
        dateVariation: 1,
        firstFlightNumber: 6497,
        operatingCarriers: ["IB"],
        prices: [
          {
            category: "ECONOMY",
            passenger: "ADULT",
            value: 5016.74,
            differenceValue: null,
            currency: "BRL",
            classType: "PUBLIC",
          },
        ],
        baggage: [
          {
            category: "ECONOMY",
            quantity: 1,
            weight: null,
          },
        ],
        connection: 2,
        hasExchangeAirport: false,
        throughFlight: 0,
        fareOriginType: "PUBLIC",
        recommendations: [
          {
            departureCategory: "ECONOMY",
            departureBookingClass: "M",
            returnFlights: null,
            fee: {
              total: {
                value: 166.95,
                currency: "BRL",
              },
            },
            fare: {
              "537": {
                cabinProduct: "M",
                classOfService: "L",
                fareBasis: "LDL0NOM7",
                fareTypes: ["RP"],
              },
              "6497": {
                cabinProduct: "M",
                classOfService: "O",
                fareBasis: "LDL0NOM7",
                fareTypes: ["RP"],
              },
              "6540": {
                cabinProduct: "M",
                classOfService: "L",
                fareBasis: "LDL0NOM7",
                fareTypes: ["RP"],
              },
            },
            validateCompany: "IB",
            othersFee: [],
          },
        ],
        flightGroup: [
          {
            flightNumber: 6497,
            origin: "FOR",
            originAirportName: "Pinto Martins International, Fortaleza - BR",
            destination: "GRU",
            destinationAirportName: "Guarulhos Intl, Sao Paulo-Guarulhos - BR",
            departureDate: "26/11/2024",
            departureTime: "11:40",
            arrivalDate: "26/11/2024",
            arrivalTime: "15:10",
            dateVariation: 0,
            marketingCarrier: "IB",
            operatingCarrier: "IB",
            hasExchangeAirport: false,
            throughFlight: false,
          },
          {
            flightNumber: 6540,
            origin: "GRU",
            originAirportName: "Guarulhos Intl, Sao Paulo-Guarulhos - BR",
            destination: "MAD",
            destinationAirportName: "Adolfo Suarez-Barajas, Madrid - ES",
            departureDate: "26/11/2024",
            departureTime: "23:30",
            arrivalDate: "27/11/2024",
            arrivalTime: "13:30",
            dateVariation: 1,
            marketingCarrier: "IB",
            operatingCarrier: "IB",
            hasExchangeAirport: false,
            throughFlight: false,
          },
          {
            flightNumber: 537,
            origin: "MAD",
            originAirportName: "Adolfo Suarez-Barajas, Madrid - ES",
            destination: "LIS",
            destinationAirportName: "Lisboa, Lisbon - PT",
            departureDate: "27/11/2024",
            departureTime: "19:40",
            arrivalDate: "27/11/2024",
            arrivalTime: "20:05",
            dateVariation: 0,
            marketingCarrier: "IB",
            operatingCarrier: "IB",
            hasExchangeAirport: false,
            throughFlight: false,
          },
        ],
        elapsedFlightTime: "2925",
      },
      {
        id: 17,
        originAirport: "FOR",
        originAirportName: "Pinto Martins International, Fortaleza - BR",
        finalDestination: "LIS",
        finalDestinationName: "Lisboa, Lisbon - PT",
        departureDate: "26/11/2024",
        departureTime: "11:40",
        finalArrivalDate: "27/11/2024",
        finalArrivalTime: "23:25",
        dateVariation: 1,
        firstFlightNumber: 6497,
        operatingCarriers: ["IB"],
        prices: [
          {
            category: "ECONOMY",
            passenger: "ADULT",
            value: 5016.74,
            differenceValue: null,
            currency: "BRL",
            classType: "PUBLIC",
          },
        ],
        baggage: [
          {
            category: "ECONOMY",
            quantity: 1,
            weight: null,
          },
        ],
        connection: 2,
        hasExchangeAirport: false,
        throughFlight: 0,
        fareOriginType: "PUBLIC",
        recommendations: [
          {
            departureCategory: "ECONOMY",
            departureBookingClass: "M",
            returnFlights: null,
            fee: {
              total: {
                value: 166.95,
                currency: "BRL",
              },
            },
            fare: {
              "539": {
                cabinProduct: "M",
                classOfService: "L",
                fareBasis: "LDL0NOM7",
                fareTypes: ["RP"],
              },
              "6497": {
                cabinProduct: "M",
                classOfService: "O",
                fareBasis: "LDL0NOM7",
                fareTypes: ["RP"],
              },
              "6540": {
                cabinProduct: "M",
                classOfService: "L",
                fareBasis: "LDL0NOM7",
                fareTypes: ["RP"],
              },
            },
            validateCompany: "IB",
            othersFee: [],
          },
        ],
        flightGroup: [
          {
            flightNumber: 6497,
            origin: "FOR",
            originAirportName: "Pinto Martins International, Fortaleza - BR",
            destination: "GRU",
            destinationAirportName: "Guarulhos Intl, Sao Paulo-Guarulhos - BR",
            departureDate: "26/11/2024",
            departureTime: "11:40",
            arrivalDate: "26/11/2024",
            arrivalTime: "15:10",
            dateVariation: 0,
            marketingCarrier: "IB",
            operatingCarrier: "IB",
            hasExchangeAirport: false,
            throughFlight: false,
          },
          {
            flightNumber: 6540,
            origin: "GRU",
            originAirportName: "Guarulhos Intl, Sao Paulo-Guarulhos - BR",
            destination: "MAD",
            destinationAirportName: "Adolfo Suarez-Barajas, Madrid - ES",
            departureDate: "26/11/2024",
            departureTime: "23:30",
            arrivalDate: "27/11/2024",
            arrivalTime: "13:30",
            dateVariation: 1,
            marketingCarrier: "IB",
            operatingCarrier: "IB",
            hasExchangeAirport: false,
            throughFlight: false,
          },
          {
            flightNumber: 539,
            origin: "MAD",
            originAirportName: "Adolfo Suarez-Barajas, Madrid - ES",
            destination: "LIS",
            destinationAirportName: "Lisboa, Lisbon - PT",
            departureDate: "27/11/2024",
            departureTime: "23:00",
            arrivalDate: "27/11/2024",
            arrivalTime: "23:25",
            dateVariation: 0,
            marketingCarrier: "IB",
            operatingCarrier: "IB",
            hasExchangeAirport: false,
            throughFlight: false,
          },
        ],
        elapsedFlightTime: "3245",
      },
      {
        id: 18,
        originAirport: "FOR",
        originAirportName: "Pinto Martins International, Fortaleza - BR",
        finalDestination: "LIS",
        finalDestinationName: "Lisboa, Lisbon - PT",
        departureDate: "26/11/2024",
        departureTime: "11:40",
        finalArrivalDate: "27/11/2024",
        finalArrivalTime: "23:25",
        dateVariation: 1,
        firstFlightNumber: 6497,
        operatingCarriers: ["IB"],
        prices: [
          {
            category: "ECONOMY",
            passenger: "ADULT",
            value: 5016.74,
            differenceValue: null,
            currency: "BRL",
            classType: "PUBLIC",
          },
        ],
        baggage: [
          {
            category: "ECONOMY",
            quantity: 1,
            weight: null,
          },
        ],
        connection: 2,
        hasExchangeAirport: false,
        throughFlight: 0,
        fareOriginType: "PUBLIC",
        recommendations: [
          {
            departureCategory: "ECONOMY",
            departureBookingClass: "M",
            returnFlights: null,
            fee: {
              total: {
                value: 203.5,
                currency: "BRL",
              },
            },
            fare: {
              "272": {
                cabinProduct: "M",
                classOfService: "L",
                fareBasis: "LDL0NOM7",
                fareTypes: ["RP"],
              },
              "539": {
                cabinProduct: "M",
                classOfService: "L",
                fareBasis: "LDL0NOM7",
                fareTypes: ["RP"],
              },
              "6497": {
                cabinProduct: "M",
                classOfService: "O",
                fareBasis: "LDL0NOM7",
                fareTypes: ["RP"],
              },
            },
            validateCompany: "IB",
            othersFee: [],
          },
        ],
        flightGroup: [
          {
            flightNumber: 6497,
            origin: "FOR",
            originAirportName: "Pinto Martins International, Fortaleza - BR",
            destination: "GRU",
            destinationAirportName: "Guarulhos Intl, Sao Paulo-Guarulhos - BR",
            departureDate: "26/11/2024",
            departureTime: "11:40",
            arrivalDate: "26/11/2024",
            arrivalTime: "15:10",
            dateVariation: 0,
            marketingCarrier: "IB",
            operatingCarrier: "IB",
            hasExchangeAirport: false,
            throughFlight: false,
          },
          {
            flightNumber: 272,
            origin: "GRU",
            originAirportName: "Guarulhos Intl, Sao Paulo-Guarulhos - BR",
            destination: "MAD",
            destinationAirportName: "Adolfo Suarez-Barajas, Madrid - ES",
            departureDate: "26/11/2024",
            departureTime: "20:30",
            arrivalDate: "27/11/2024",
            arrivalTime: "10:35",
            dateVariation: 1,
            marketingCarrier: "IB",
            operatingCarrier: "IB",
            hasExchangeAirport: false,
            throughFlight: false,
          },
          {
            flightNumber: 539,
            origin: "MAD",
            originAirportName: "Adolfo Suarez-Barajas, Madrid - ES",
            destination: "LIS",
            destinationAirportName: "Lisboa, Lisbon - PT",
            departureDate: "27/11/2024",
            departureTime: "23:00",
            arrivalDate: "27/11/2024",
            arrivalTime: "23:25",
            dateVariation: 0,
            marketingCarrier: "IB",
            operatingCarrier: "IB",
            hasExchangeAirport: false,
            throughFlight: false,
          },
        ],
        elapsedFlightTime: "3245",
      },
      {
        id: 19,
        originAirport: "FOR",
        originAirportName: "Pinto Martins International, Fortaleza - BR",
        finalDestination: "LIS",
        finalDestinationName: "Lisboa, Lisbon - PT",
        departureDate: "26/11/2024",
        departureTime: "11:40",
        finalArrivalDate: "28/11/2024",
        finalArrivalTime: "07:45",
        dateVariation: 2,
        firstFlightNumber: 6497,
        operatingCarriers: ["IB"],
        prices: [
          {
            category: "ECONOMY",
            passenger: "ADULT",
            value: 5016.74,
            differenceValue: null,
            currency: "BRL",
            classType: "PUBLIC",
          },
        ],
        baggage: [
          {
            category: "ECONOMY",
            quantity: 1,
            weight: null,
          },
        ],
        connection: 2,
        hasExchangeAirport: false,
        throughFlight: 0,
        fareOriginType: "PUBLIC",
        recommendations: [
          {
            departureCategory: "ECONOMY",
            departureBookingClass: "M",
            returnFlights: null,
            fee: {
              total: {
                value: 203.5,
                currency: "BRL",
              },
            },
            fare: {
              "272": {
                cabinProduct: "M",
                classOfService: "L",
                fareBasis: "LDL0NOM7",
                fareTypes: ["RP"],
              },
              "529": {
                cabinProduct: "M",
                classOfService: "L",
                fareBasis: "LDL0NOM7",
                fareTypes: ["RP"],
              },
              "6497": {
                cabinProduct: "M",
                classOfService: "O",
                fareBasis: "LDL0NOM7",
                fareTypes: ["RP"],
              },
            },
            validateCompany: "IB",
            othersFee: [],
          },
        ],
        flightGroup: [
          {
            flightNumber: 6497,
            origin: "FOR",
            originAirportName: "Pinto Martins International, Fortaleza - BR",
            destination: "GRU",
            destinationAirportName: "Guarulhos Intl, Sao Paulo-Guarulhos - BR",
            departureDate: "26/11/2024",
            departureTime: "11:40",
            arrivalDate: "26/11/2024",
            arrivalTime: "15:10",
            dateVariation: 0,
            marketingCarrier: "IB",
            operatingCarrier: "IB",
            hasExchangeAirport: false,
            throughFlight: false,
          },
          {
            flightNumber: 272,
            origin: "GRU",
            originAirportName: "Guarulhos Intl, Sao Paulo-Guarulhos - BR",
            destination: "MAD",
            destinationAirportName: "Adolfo Suarez-Barajas, Madrid - ES",
            departureDate: "26/11/2024",
            departureTime: "20:30",
            arrivalDate: "27/11/2024",
            arrivalTime: "10:35",
            dateVariation: 1,
            marketingCarrier: "IB",
            operatingCarrier: "IB",
            hasExchangeAirport: false,
            throughFlight: false,
          },
          {
            flightNumber: 529,
            origin: "MAD",
            originAirportName: "Adolfo Suarez-Barajas, Madrid - ES",
            destination: "LIS",
            destinationAirportName: "Lisboa, Lisbon - PT",
            departureDate: "28/11/2024",
            departureTime: "07:20",
            arrivalDate: "28/11/2024",
            arrivalTime: "07:45",
            dateVariation: 0,
            marketingCarrier: "IB",
            operatingCarrier: "IB",
            hasExchangeAirport: false,
            throughFlight: false,
          },
        ],
        elapsedFlightTime: "4105",
      },
      {
        id: 20,
        originAirport: "FOR",
        originAirportName: "Pinto Martins International, Fortaleza - BR",
        finalDestination: "LIS",
        finalDestinationName: "Lisboa, Lisbon - PT",
        departureDate: "26/11/2024",
        departureTime: "11:40",
        finalArrivalDate: "28/11/2024",
        finalArrivalTime: "07:45",
        dateVariation: 2,
        firstFlightNumber: 6497,
        operatingCarriers: ["IB"],
        prices: [
          {
            category: "ECONOMY",
            passenger: "ADULT",
            value: 5016.74,
            differenceValue: null,
            currency: "BRL",
            classType: "PUBLIC",
          },
        ],
        baggage: [
          {
            category: "ECONOMY",
            quantity: 1,
            weight: null,
          },
        ],
        connection: 2,
        hasExchangeAirport: false,
        throughFlight: 0,
        fareOriginType: "PUBLIC",
        recommendations: [
          {
            departureCategory: "ECONOMY",
            departureBookingClass: "M",
            returnFlights: null,
            fee: {
              total: {
                value: 203.5,
                currency: "BRL",
              },
            },
            fare: {
              "529": {
                cabinProduct: "M",
                classOfService: "L",
                fareBasis: "LDL0NOM7",
                fareTypes: ["RP"],
              },
              "6497": {
                cabinProduct: "M",
                classOfService: "O",
                fareBasis: "LDL0NOM7",
                fareTypes: ["RP"],
              },
              "6540": {
                cabinProduct: "M",
                classOfService: "L",
                fareBasis: "LDL0NOM7",
                fareTypes: ["RP"],
              },
            },
            validateCompany: "IB",
            othersFee: [],
          },
        ],
        flightGroup: [
          {
            flightNumber: 6497,
            origin: "FOR",
            originAirportName: "Pinto Martins International, Fortaleza - BR",
            destination: "GRU",
            destinationAirportName: "Guarulhos Intl, Sao Paulo-Guarulhos - BR",
            departureDate: "26/11/2024",
            departureTime: "11:40",
            arrivalDate: "26/11/2024",
            arrivalTime: "15:10",
            dateVariation: 0,
            marketingCarrier: "IB",
            operatingCarrier: "IB",
            hasExchangeAirport: false,
            throughFlight: false,
          },
          {
            flightNumber: 6540,
            origin: "GRU",
            originAirportName: "Guarulhos Intl, Sao Paulo-Guarulhos - BR",
            destination: "MAD",
            destinationAirportName: "Adolfo Suarez-Barajas, Madrid - ES",
            departureDate: "26/11/2024",
            departureTime: "23:30",
            arrivalDate: "27/11/2024",
            arrivalTime: "13:30",
            dateVariation: 1,
            marketingCarrier: "IB",
            operatingCarrier: "IB",
            hasExchangeAirport: false,
            throughFlight: false,
          },
          {
            flightNumber: 529,
            origin: "MAD",
            originAirportName: "Adolfo Suarez-Barajas, Madrid - ES",
            destination: "LIS",
            destinationAirportName: "Lisboa, Lisbon - PT",
            departureDate: "28/11/2024",
            departureTime: "07:20",
            arrivalDate: "28/11/2024",
            arrivalTime: "07:45",
            dateVariation: 0,
            marketingCarrier: "IB",
            operatingCarrier: "IB",
            hasExchangeAirport: false,
            throughFlight: false,
          },
        ],
        elapsedFlightTime: "4105",
      },
      {
        id: 21,
        originAirport: "FOR",
        originAirportName: "Pinto Martins International, Fortaleza - BR",
        finalDestination: "LIS",
        finalDestinationName: "Lisboa, Lisbon - PT",
        departureDate: "26/11/2024",
        departureTime: "11:40",
        finalArrivalDate: "28/11/2024",
        finalArrivalTime: "11:50",
        dateVariation: 2,
        firstFlightNumber: 6497,
        operatingCarriers: ["IB"],
        prices: [
          {
            category: "ECONOMY",
            passenger: "ADULT",
            value: 5016.74,
            differenceValue: null,
            currency: "BRL",
            classType: "PUBLIC",
          },
        ],
        baggage: [
          {
            category: "ECONOMY",
            quantity: 1,
            weight: null,
          },
        ],
        connection: 2,
        hasExchangeAirport: false,
        throughFlight: 0,
        fareOriginType: "PUBLIC",
        recommendations: [
          {
            departureCategory: "ECONOMY",
            departureBookingClass: "M",
            returnFlights: null,
            fee: {
              total: {
                value: 203.5,
                currency: "BRL",
              },
            },
            fare: {
              "531": {
                cabinProduct: "M",
                classOfService: "L",
                fareBasis: "LDL0NOM7",
                fareTypes: ["RP"],
              },
              "6497": {
                cabinProduct: "M",
                classOfService: "O",
                fareBasis: "LDL0NOM7",
                fareTypes: ["RP"],
              },
              "6540": {
                cabinProduct: "M",
                classOfService: "L",
                fareBasis: "LDL0NOM7",
                fareTypes: ["RP"],
              },
            },
            validateCompany: "IB",
            othersFee: [],
          },
        ],
        flightGroup: [
          {
            flightNumber: 6497,
            origin: "FOR",
            originAirportName: "Pinto Martins International, Fortaleza - BR",
            destination: "GRU",
            destinationAirportName: "Guarulhos Intl, Sao Paulo-Guarulhos - BR",
            departureDate: "26/11/2024",
            departureTime: "11:40",
            arrivalDate: "26/11/2024",
            arrivalTime: "15:10",
            dateVariation: 0,
            marketingCarrier: "IB",
            operatingCarrier: "IB",
            hasExchangeAirport: false,
            throughFlight: false,
          },
          {
            flightNumber: 6540,
            origin: "GRU",
            originAirportName: "Guarulhos Intl, Sao Paulo-Guarulhos - BR",
            destination: "MAD",
            destinationAirportName: "Adolfo Suarez-Barajas, Madrid - ES",
            departureDate: "26/11/2024",
            departureTime: "23:30",
            arrivalDate: "27/11/2024",
            arrivalTime: "13:30",
            dateVariation: 1,
            marketingCarrier: "IB",
            operatingCarrier: "IB",
            hasExchangeAirport: false,
            throughFlight: false,
          },
          {
            flightNumber: 531,
            origin: "MAD",
            originAirportName: "Adolfo Suarez-Barajas, Madrid - ES",
            destination: "LIS",
            destinationAirportName: "Lisboa, Lisbon - PT",
            departureDate: "28/11/2024",
            departureTime: "11:25",
            arrivalDate: "28/11/2024",
            arrivalTime: "11:50",
            dateVariation: 0,
            marketingCarrier: "IB",
            operatingCarrier: "IB",
            hasExchangeAirport: false,
            throughFlight: false,
          },
        ],
        elapsedFlightTime: "4510",
      },
    ],
  },
  returnFlights: {
    date: null,
    flights: [],
  },
};
